name: Deploy Static HTML Version

on:
  push:
    branches:
      - main
      - v1.1
      - v1.2
      - v1.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy  # This branch will be created automatically
          publish_dir: ./         # Root directory (adjust if files are inside a subfolder)
          destination_dir: ${{ github.ref_name }}  # Puts files in /main/, /v1.1/, etc.
          keep_files: true  # Keeps existing versions in the deploy branch
