name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main
      - v1.1
      - v1.2
      - v1.3

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Prepare versioned folder for deployment
      - name: Prepare versioned folder
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
          mkdir -p deploy/$BRANCH_NAME
          rsync -av --exclude='deploy' ./ deploy/$BRANCH_NAME/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
