name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main
      - v1.1
      - v1.2
      - v1.3

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code of the current branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Prepare versioned folder (based on branch name)
      - name: Prepare versioned folder
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
          mkdir -p "deploy/$BRANCH_NAME"
          rsync -av --exclude='deploy' --exclude='.git' --exclude='.github' ./ "deploy/$BRANCH_NAME/"

      # Step 4: Checkout the gh-pages branch (ensure it's up-to-date)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # Step 5: Copy new branch contents into gh-pages
      - name: Copy version folder to gh-pages
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
          rsync -av --exclude='.git' --exclude='.github' "deploy/$BRANCH_NAME/" ./ 
          git add .
          git commit -m "Deploy $BRANCH_NAME to gh-pages"
          git push origin gh-pages

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
