name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main
      - v1.1
      - v1.2
      - v1.3

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code of the current branch (main, v1.1, v1.2, etc.)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Prepare versioned folder for the current branch (main, v1.1, etc.)
      - name: Prepare versioned folder
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
          mkdir -p "deploy/$BRANCH_NAME"
          rsync -av --exclude='deploy' --exclude='.git' --exclude='.github' ./ "deploy/$BRANCH_NAME/"

      # Step 3: Setup GitHub Pages using the specific folder for the branch
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: ${{ github.ref_name }}  # Deploy from the current branch
          folder: "deploy/${{ github.ref_name }}"  # Use the specific folder for each version
